import httpx
import os
import json
import re
import asyncio
from typing import Optional, Dict, Any
from apps.api.core.concurrency import governor, Priority
from apps.api.core.model_router import model_router

OLLAMA_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
DEFAULT_TIMEOUT = float(os.getenv("OLLAMA_TIMEOUT", "120.0"))

class OllamaClient:
    def __init__(self, timeout: float = DEFAULT_TIMEOUT):
        self.timeout = httpx.Timeout(timeout, connect=5.0)
        self.router = model_router
        
    async def is_available(self) -> bool:
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                response = await client.get(f"{OLLAMA_URL}/api/tags")
                return response.status_code == 200
        except Exception:
            return False

    async def generate(self, prompt: str, task_complexity: str = "light", structured_format: Optional[str] = None, priority: int = Priority.INTERACTIVE) -> Dict[str, Any]:
        # Acquire QoS lock based on priority
        await governor.acquire(priority)
        try:
            # Standalone Model Router with fallback cascade (Patch P-08)
            chosen_model = self.router.resolve_model(task_complexity)

            # Local-only / zero-egress safety check
            if "localhost" not in OLLAMA_URL and "127.0.0.1" not in OLLAMA_URL:
                 return {"success": False, "error": "Zero-egress violation: OLLAMA_BASE_URL must be local."}

            payload = {
                "model": chosen_model,
                "prompt": prompt,
                "stream": False,
                "keep_alive": -1,
                "options": {
                    "num_predict": 600,
                    "temperature": 0.2,
                }
            }
            if structured_format:
                payload["format"] = "json"
                
            # Allow longer timeout for deep reasoning tasks on local machines
            request_timeout = self.timeout
            if task_complexity in ("deep", "reasoning", "heavy", "complex"):
                read_timeout = max(self.timeout.read or 120.0, 180.0)
                request_timeout = httpx.Timeout(read_timeout, connect=5.0)

            async with httpx.AsyncClient(timeout=request_timeout) as client:
                response = await client.post(f"{OLLAMA_URL}/api/generate", json=payload)
                response.raise_for_status()
                result = response.json()
                raw_text = result.get("response", "")
                if not raw_text or not raw_text.strip():
                    raw_text = result.get("thinking", "")
                
                if structured_format == "json":
                    try:
                        # Clean out thinking blocks and markdown fences if generated by reasoning models (e.g. Qwen3)
                        cleaned_json = re.sub(r"<thought>[\s\S]*?</thought>", "", raw_text).strip()
                        match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned_json)
                        if match:
                            cleaned_json = match.group(1).strip()
                        
                        try:
                            parsed_json = json.loads(cleaned_json)
                        except json.JSONDecodeError:
                            s = cleaned_json.find("{")
                            e = cleaned_json.rfind("}")
                            if s != -1 and e != -1 and e > s:
                                parsed_json = json.loads(cleaned_json[s:e+1])
                            else:
                                s_arr = cleaned_json.find("[")
                                e_arr = cleaned_json.rfind("]")
                                if s_arr != -1 and e_arr != -1 and e_arr > s_arr:
                                    parsed_json = json.loads(cleaned_json[s_arr:e_arr+1])
                                else:
                                    raise
                        return {"success": True, "response": parsed_json, "model_used": chosen_model}
                    except Exception:
                        return {"success": False, "error": "Invalid JSON response", "raw": raw_text, "model_used": chosen_model}
                
                # For free-form text, strip <thought> tags from clean output if present
                clean_text = re.sub(r"<thought>[\s\S]*?</thought>", "", raw_text).strip()
                if not clean_text and raw_text:
                    clean_text = raw_text.strip()

                return {"success": True, "response": clean_text, "model_used": chosen_model}
        except httpx.HTTPError as e:
            err_detail = str(e) if str(e) else e.__class__.__name__
            return {"success": False, "error": f"Local model unavailable: {err_detail}"}
        except Exception as e:
            return {"success": False, "error": str(e)}
        finally:
            await governor.release()

ollama_client = OllamaClient()
