# apps/api/cortex/madr_writer.py
"""Living Architecture Decision Record (MADR) Generator.

Auto-synthesizes versioned Markdown ADRs in docs/adr/ when architectural breaches
or design trade-offs are committed, using local Ollama Qwen3 8B with an offline fallback.
"""
import os
import re
import time
from pathlib import Path
from typing import Dict, Any, Optional
import httpx


class MadrWriter:
    """Generates and maintains Markdown Architecture Decision Records."""

    def __init__(self, root_dir: Optional[Path] = None, ollama_url: str = "http://localhost:11434"):
        self.root_dir = root_dir or Path(__file__).resolve().parents[3]
        self.adr_dir = self.root_dir / "docs" / "adr"
        self.ollama_url = ollama_url
        os.makedirs(self.adr_dir, exist_ok=True)

    def generate_madr(
        self,
        rule_id: str,
        rule_name: str,
        violating_file: str,
        rationale: str,
        suggested_refactor: str,
        author: str = "Arya <salimattarya@gmail.com>",
    ) -> str:
        """Synthesizes a Living MADR and writes it to docs/adr/."""
        # Clean slug
        clean_name = re.sub(r'[^a-zA-Z0-9]+', '-', rule_name.lower()).strip('-')
        file_name = f"{rule_id.lower()}-{clean_name}.md"
        target_path = self.adr_dir / file_name

        # Attempt to synthesize enhanced narrative via local Ollama
        enhanced_explanation = self._query_local_ollama(rule_id, rule_name, violating_file, rationale)
        if not enhanced_explanation:
            enhanced_explanation = rationale

        madr_content = f"""# {rule_id}: {rule_name}

* **Status:** Accepted / Enforced by TARS Deterministic Sentinel
* **Date:** {time.strftime('%Y-%m-%d')}
* **Author:** {author}
* **Target Scope:** `{violating_file}`
* **Enforcement Engine:** Tree-sitter C-AST (<45ms) + Kùzu Graph

## Context and Problem Statement
When developing features touching `{violating_file}`, architectural constraints must be preserved.
{enhanced_explanation}

## Decision Drivers
* **System Resilience:** Prevent cascading production outages and connection pool exhaustion.
* **Deterministic Governance:** Enforce invariants locally in pre-commit git hooks in <50ms.
* **Zero Cloud Egress:** 100% air-gapped verification on local silicon.

## Considered Options
1. **Unconstrained Code Generation:** Rely on developer diligence and human code review (High regression risk).
2. **Deterministic TARS Pre-Commit Invariant:** Intercept prohibited concrete syntax patterns at commit time (Chosen).

## Decision Outcome
Chosen option: **Enforce {rule_id} via TARS Invariant Rulepack**.

### Positive Consequences
* Completely eliminates structural regressions before code enters version control.
* Provides immediate sub-50ms remediation feedback directly in the developer's terminal.

### Remediation & Suggested Refactor
```text
{suggested_refactor}
```

## Architectural Links
* Invariant Reference: `.tars/invariants.yaml` ({rule_id})
* Provenance: Auto-generated by TARS Cortex Sentinel
"""
        with open(target_path, "w", encoding="utf-8") as f:
            f.write(madr_content)

        return str(target_path)

    def _query_local_ollama(self, rule_id: str, rule_name: str, file_path: str, rationale: str) -> Optional[str]:
        """Queries local Ollama (Qwen 8B) for high-speed rationale expansion with a 1.8s timeout."""
        prompt = f"""You are TARS, a local sovereign codebase sentinel.
Explain why violating '{rule_name}' ({rule_id}) in file '{file_path}' causes production failures.
Original rationale: {rationale}
Provide a crisp, 2-paragraph technical explanation focusing on concurrency, connection pools, and modularity."""

        try:
            with httpx.Client(timeout=1.8) as client:
                res = client.post(
                    f"{self.ollama_url}/api/generate",
                    json={
                        "model": "qwen2.5:8b",
                        "prompt": prompt,
                        "stream": False,
                    }
                )
                if res.status_code == 200:
                    return res.json().get("response", "").strip()
        except Exception:
            # Offline fallback - Ollama is optional, determinism is guaranteed
            pass

        return None
